#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const specDir = path.join(__dirname, "../spec/mustache/specs");
const outputDir = path.join(__dirname, "../spec/generated");

// Files to generate tests for
const enabledFiles = ["comments.json", "interpolation.json"];

// Ensure output directory exists
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

function escapeString(str) {
  return str
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$/g, "\\$");
}

function generateTestFile(jsonFile) {
  const specPath = path.join(specDir, jsonFile);
  const spec = JSON.parse(fs.readFileSync(specPath, "utf8"));
  
  const baseName = path.basename(jsonFile, ".json");
  const outputPath = path.join(outputDir, `${baseName}.spec.ts`);
  
  let output = `// Auto-generated test file from ${jsonFile}\n`;
  output += `// DO NOT EDIT - This file is generated by scripts/generate-tests.js\n\n`;
  output += `import { interp } from "../../src/index";\n\n`;
  output += `describe("${baseName}", () => {\n`;
  
  spec.tests.forEach((test) => {
    const testName = test.name.replace(/"/g, '\\"');
    const template = escapeString(test.template);
    const expected = escapeString(test.expected);
    const dataStr = JSON.stringify(test.data, null, 2)
      .split('\n')
      .map((line, idx) => idx === 0 ? line : '    ' + line)
      .join('\n');
    
    output += `  it("${testName}", () => {\n`;
    
    if (test.data && typeof test.data === 'object' && test.data.lambda) {
      // Handle lambda case
      output += `    const data: any = ${dataStr};\n`;
      output += `    data.lambda = ${test.data.lambda.js};\n`;
    } else {
      // Use 'any' type for data to allow primitives
      output += `    const data: any = ${dataStr};\n`;
    }
    
    output += `    const template = \`${template}\`;\n`;
    output += `    const expected = \`${expected}\`;\n`;
    output += `    expect(interp(template, data)).toBe(expected);\n`;
    output += `  });\n\n`;
  });
  
  output += `});\n`;
  
  fs.writeFileSync(outputPath, output, "utf8");
  console.log(`Generated: ${outputPath}`);
}

// Generate tests for enabled files
enabledFiles.forEach((file) => {
  generateTestFile(file);
});

console.log("\nTest generation complete!");
